### ISSUE TITLE
It occurred an error when I build it in cmake, how should I do? Thanks

### ISSUE THREAD

**Issue by pengzhendong** [openscenegraph/osgQt#1]
C:\Users\Randy\Desktop\osgQt\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\Randy\Desktop\osgQt\build\CMakeFiles\CMakeTmp\cmTC_13edd.vcxproj]

**Comment by internetscooter** [comment]
I have done a hack here but I have not followed through to see if it actually works...

[osgQT - Windows 10 pthread.h - not found](http://forum.openscenegraph.org/viewtopic.php?t=16305)

**Comment by pengzhendong** [comment]
Thanks, I have read that solution, but it did not output any information in message("CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")

**Comment by pengzhendong** [comment]
Thank you very much, hope it work for my curriculum design.

**Comment by mathieu** [comment]
Have you worked it out now ?

**Comment by pengzhendong** [comment]
I am sorry. I didn't work it out now and I have given up.
