### ISSUE TITLE
Qt5 QOpenGLWidget

### ISSUE THREAD

**Issue by NobilisNC** [openscenegraph/osgQt#17]
Is it possible to add a `OpenGLWidget` which inherit from `QOpenGLWidget` for QT5 because currently the `GLWidget` inherit from `QGLWidget` which has been deprecated.

Do you have some clue to do this ? 
I saw some code with `QOpenGLWidget` but all of them use a `osgVierwer::Viewer`, but I need to use a `osgViewer::CompositeViewer` and add each `osgViewer::View` in a Qt5 widget.

The job is actually done with a QGLWidget, but they are a lot of glitches due to the complexity of the window structure and an upgrade to `QOpenGLWidget` will normaly fix them.

Thanks,
Tom

**Comment by gusmd** [comment]
I know this is old, but take a look at https://github.com/openscenegraph/osgQt/pull/22. It does exactly that.

**Comment by mathieu** [comment]
master branch has the Qt5 way of doing this

**Comment by pablocael** [comment]
Hi there, this might be related topic: I have issues using QOpenGLWidget and OSG RTT (render to texture). It seems that QOpenGLWidget uses FBO internally and osg::Camera manages it as well, resulting in some sort of conflict. 
Is there way of solving that? I can use my RTT app with QGLWidget, but switching to QOpenGLWidget make FBO render to texture stop working.
