### ISSUE TITLE
how to use osgqopengl in osgearth project ？

### ISSUE THREAD

**Issue by qiup-Q** [openscenegraph/osgQt#31]
osgQOpenGL is not compatible with osgEarthQt or simdissdk/simQt ，i want to use osgOpenGL API to update these project，but i found it's difficult .
I will do this, because I found some animation like triton ocean or 3D model with animation in it (like helicopters) will not animated anymore, but when I use osgQOpenGL’s osgviewqt to load animated 3D model, it same like normal, I think if I use OsgQOpenGL to instead of osgQt the problems in my project about ocean Or model animation errors may be fixed.

**Comment by qiup-Q** [comment]
Forgive me for my bed english.
I’m confused with how to use osgQOpenGL API   in some project like osgearth , Do you have some options or more document about it?

**Comment by mathieu** [comment]
osgQt is compatible with osgEarth, you will need to have OSG compiled with modern OpenGL support thought (CMake GL3 option I think)
