### ISSUE TITLE
win10 + vs2017 download Pakege faild by winhttpsendrequest error 12092

### ISSUE THREAD

**Issue by DoMissHome** [openscenegraph/osgQt#34]
win10 + vs2017 download Pakege faild by winhttpsendrequest error 12092

**Comment by DoMissHome** [comment]
help,help ,please help me ,thank you

**Comment by openscenegraph** [comment]
You'll need to give us an URL of where you are downloading a package otherwise we have no way of knowing what may have failed, whether it has anything to do with the OSG project.  

FYI, the OSG project itself doesn't provide binary packages, those that do exist are provided by 3rd parties.

**Comment by mathieu** [comment]
Looks like the @DoMissHome is using and referring to [microsoft/vcpkg](https://github.com/microsoft/vcpkg).

@DoMissHome please open your issue over there

**Comment by DoMissHome** [comment]
Yes ,I get that problem when I download some library by vcpkg ，like WinHttpSendRequest() faild:12029
