### ISSUE TITLE
Library named libosgQt5.so on linux, FindOpenSceneGraph.cmake looks for libosgQt.so

### ISSUE THREAD

**Issue by gusmd** [openscenegraph/osgQt#5]
Hi everyone,

The title sums it up. I've build OpenSceneGraph and osgQt from source today on Ubuntu 17.04. The resulting libraries from osgQt on my system with Qt 5.9 are named "libosgQt5.so", "libosgQt5.so.3.5.6", and "libosgQt5.so.145". But FindOpenSceneGraph for CMake will not find osgQt with that naming. I had to rename libosgQt5.so to libosgQt.so so that CMake would find it when using `find_package(OpenSceneGraph REQUIRED COMPONENTS osgQt)`.

**Comment by stefkeB** [comment]
In the FindosgQt.cmake file, there is `OSG_FIND_LIBRARY(OSGQT osgqt)`which should be `osgqt5` to find the Qt5 library with it's new name.

**Comment by gusmd** [comment]
@stefkeB thanks for the reply! You are right.

I just had the same problem again today when building osg + osgQt on Windows. Locally, I could fix it one of three ways:

1. Edit FindosgQt.cmake with the change you mentioned, or
2. Rename my libs to remove the "5" (like in my original post above), or
3. Add the following code to my CMakeLists to find the correct osgQt5.lib on Windows:

```
if (WIN32)
    find_library(OSGQT_LIBRARY
        NAMES osgQt5.lib
        PATHS ENV OSG_LIB_PATH
    )
    find_library(OSGQT_LIBRARY_DEBUG
        NAMES osgQt5d.lib
        PATHS ENV OSG_LIB_PATH
    )
endif()
```

There I take advantage of my already set OSG_LIB_PATH environment variable and just reuse it for finding osgQt5/d.lib.

Then right after that I have the usual: `find_package(OpenSceneGraph REQUIRED COMPONENTS osgDB osgGA osgUtil osgViewer osgQt osgFX)
`

Don't you think we should make option (1) above the default by contributing this to CMake?

**Comment by stefkeB** [comment]
I think the first option is indeed the cleanest. Do you still take Qt4 libraries into account? As some projects are still in Qt4, I guess this caused the current Qt5 naming scheme.

**Comment by gusmd** [comment]
I personally do not use Qt4, but I guess osgQt still supports it.

You are right; if you build osgQt with Qt4, the library is called osgQt.lib/so, instead of osgQt5.lib/so, as can be seen in osgQt/src/osgQt/CMakeLists.txt @ 8:

```cmake
IF ( Qt5Widgets_FOUND )
    SET(LIB_NAME osgQt5)
    SET(HEADER_INSTALL_DIR osgQt)
ELSE()
    SET(LIB_NAME osgQt)
ENDIF()
```

I'm not sure how to resolve this. Would it make sense to fork FindosgQt.cmake to create a separate FindosgQt5.cmake? Then users could use:

```cmake
find_package(OpenSceneGraph REQUIRED COMPONENTS osgQt5)
```
For Qt5 and
```cmake
find_package(OpenSceneGraph REQUIRED COMPONENTS osgQt )
```
For Qt4?

Or is there a more elegant solution?

**Comment by mathieu** [comment]
The easy solution would be to drop support for Qt4 and only rely on Qt5 since Qt4 isn't getting any more updates.

I'm planning to open some code we made with the help of Mike Cruz from KDAB to make a QOpenGLWidget and QOpenGLWindow version of the osgViewer.

I know there are also some QML version of the viewer around, it would be nice to gather those inside this repository...

**Comment by openscenegraph** [comment]
If you do decide on dropping Qt4 then I would suggest making a branch for Qt4/Qt5 so that those who really need Qt4 support still have a convenient place to get the code/make fixes.

**Comment by gusmd** [comment]
Hi @mathieu, I'm really interested in the new osgViewer that you mentioned you wrote with KDAB's help. Any chance you can share that? Maybe start a new repository for it?

**Comment by mathieu** [comment]
hi @gusmd, I want to put it here as an example usage of osg and Qt... Need to find some time to recover from backups since my computer crash...

**Comment by mathieu** [comment]
@gusmd, have a look in my feature branch 08b021c80085bcdbf25ced81713864f799bb8671
