### ISSUE TITLE
Adding tag 3.5.7

### ISSUE THREAD

**Issue by jcarpent** [openscenegraph/osgQt#6]
@robertosfield Can you push a new tag 3.5.7  for the current version on the master branch which is finally compatible with OSG 3.5.7 and later?
I'll then create a Formula for HomeBrew.

**Comment by openscenegraph** [comment]
I'm no longer the lead on osgQt so it's not really my place to make decisions on this.

FYI, I'll be tagging OpenSceneGraph-3.5.9 this week.

**Comment by mathieu** [comment]
I’ll create it tomorrow

**Comment by jcarpent** [comment]
Ok, it sounds perfect. Thanks to both of you.

**Comment by mathieu** [comment]
Hi @robertosfield (aka @openscenegraph), I've noticed that you committed directly to master... 

Thank you for taking the time to make osgQt compatible with osg's latests changes. As lead of the project I would prefer having modifications (even trivial ones) go through the `Pull requests` mechanism if possible.

**Comment by mathieu** [comment]
@jcarpent, it is now tagged, thanks for the HomeBrew formula btw ! I will close this issue, but leave a question open for you, have you tested the CoreProfile version of OpenSceneGraph, I see from org's formula that's it's not an option ?

**Comment by openscenegraph** [comment]
@mathieu No problem with generating PRs rather than just doing a commit right away.

**Comment by jcarpent** [comment]
@mathieu Certainly I'm not an expert, but what is exactly the CoreProfile?
In between, thanks for the tag.

**Comment by mathieu** [comment]
@jcarpent it's about the accessing the modern OpenGL pipeline. (GL3) 

On macOS there are two exclusive OpenGL profiles that can be set in the graphical context :  
- Compatibility (Legacy) Profile which is OpenGL 2.1 and GLSL 1.20 only
- Core Profile which is OpenGL 4.1 and GLSL 4.10 but without any of the fixed pipeline api
