### ISSUE TITLE
Official repository

### ISSUE THREAD

**Issue by jcarpent** [openscenegraph/osgQt#7]
@openscenegraph @mathieu I want to create a PR for osgQt but I do not know on which repo I have to make it: @mathieu's repo or on the @openscenegraph?

**Comment by jcarpent** [comment]
I have tried to submit osgQt as a Formula for brew but Jenkins raises raise some issues about:
 - * GitHub fork (not canonical repository)
 - * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)

Can someone of you (@mathieu @robertosfield) create an official repository for osgQt?

Thanks in advance

**Comment by openscenegraph** [comment]
osgQt has moved out of the the main OpenSceneGraph after the OpenSceneGraph-3.4 stable relerase, so if your osgQt changes affect 3.4 then you'll need to raise a PR for it via the OpenSceneGraph repo.  For alter than 3.4 you'll need to use the osgQt repository.

As for osgQt needing an official repository, I'm a bit perplexed by this, the openscenegreaph/osgQt respository *is* the official osgQt repository.  I hasn't long been a separate project from the main OpenSceneGraph, but now it has been separated this is where it'll be developed going forward.

The main openscenegraph/OpenSceneGraph repository is at the same level as openscenegraph/osgQt, so if OpenSceneGraph is fine, then I would have though openscenegraph/osgQt should be fine, unless brew is broken and can't handle such an approach, but this isn't down to the OSG, it's a flaw in brew.

The number of forks etc. for osgQt will be down to it being a new repo spun out from a long established one, and as yet no official stable release of the OSG or osgQt associated with it.

**Comment by jcarpent** [comment]
I share your position and I want to thank you for your quick reply.
